core:
  command-aliases: 'goldencrates,crates,crate,case,cases'
  lang: en

data:
  auto-save: 15
  instant-save: false
  storage:
    type: sqlite
    username: none
    password: none
    host: none
    database: none
  purge:
    enabled: false
    days: 60

crates:
  block:
    disable-visual-drop: false
  preview:
    enabled: true
    gui:
      title: '&8%crate% Preview'
      size: 36
      reward-slots: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26
      content:
        next:
          material: ARROW
          name: '&aNext »'
          lore: []
          slots: '35'
          type: NEXT
        back:
          material: ARROW
          name: '&c« Back'
          lore: []
          slots: '27'
          type: BACK
        exit:
          material: BARRIER
          name: '&cExit'
          lore: []
          slots: '31'
          type: EXIT
    lore:
    - '&7'
    - '&e&lWin Chance: &6%chance%%'
    - '&7'
    - '%item_lore%'